package main

import (
	"crypto/ed25519"
	"os"
	"path/filepath"
	"strings"
	"testing"

	"github.com/mr-tron/base58/base58"
)

// Reference vectors generated by running the API repo's canonical
// utils.DeriveRewardManagerKeypair (api.audius.co/utils) over these inputs.
// The secrets are throwaway test values, not production material.
//
// This is the guard on a duplicated derivation. The writer cannot import the
// API's copy — different module — so the algorithm is spelled out twice, and
// the failure mode of a divergence is invisible: a wrong seed still yields a
// perfectly valid ed25519 keypair, the pool create still gets an
// rm_owner_signature, and it simply verifies against nothing. Nobody finds out
// until a validator rejects the transaction, or worse, until someone notices
// the migrated pools are unusable.
//
// If this test fails, the derivations have diverged. Do not update the
// expectations to match this repo — find out which side moved.
var rmDerivationVectors = []struct {
	name      string
	secret    string
	mint      string
	wantRM    string
	wantEthCA string // the sibling claim authority, recorded for provenance
}{
	{
		name:      "all ones",
		secret:    "1111111111111111111111111111111111111111111111111111111111111111",
		mint:      "So11111111111111111111111111111111111111112",
		wantRM:    "8CgciaguVshTciGS5xw3F5Ps6fMiKNrGnLTgcv2spWi3",
		wantEthCA: "0xAbcF85Be21aB0B82B294ecC12b2EFcBb65b3BD03",
	},
	{
		name:      "ascending nibbles",
		secret:    "0123456789abcdef0123456789abcdef0123456789abcdef0123456789abcdef",
		mint:      "EPjFWdd5AufqSSqeM2qN1xzybapC8G4wEGGkZwyTDt1v",
		wantRM:    "DYp7C22yBnPT2qLbsg2BBiM89QHRSu6onTBJYYuLRbRG",
		wantEthCA: "0x7eAF84Cf30F719e51939094ac87009Ad3Dc35669",
	},
	{
		name:      "descending nibbles",
		secret:    "fedcba9876543210fedcba9876543210fedcba9876543210fedcba9876543210",
		mint:      "9n4nbM75f5Ui33ZbPYXn59EwSgE8CGsHtAeTH5YFeJ9E",
		wantRM:    "8FizBvqUUSkg1EiNEFN9nb8AheFWFf2uvxcYjCjtTdxf",
		wantEthCA: "0xDB1fF06EaEf601F4Cc0737af739916Af5c47bBF4",
	},
}

func TestRMDerivationMatchesAPI(t *testing.T) {
	for _, v := range rmDerivationVectors {
		t.Run(v.name, func(t *testing.T) {
			mint, err := base58.Decode(v.mint)
			if err != nil {
				t.Fatalf("decode mint: %v", err)
			}
			got := base58.Encode(deriveRewardManagerKeypair(v.secret, mint).Public().(ed25519.PublicKey))
			if got != v.wantRM {
				t.Errorf("derived reward manager %s, want %s — this repo's derivation has diverged "+
					"from the API's utils.DeriveRewardManagerKeypair; rm_owner_signature would "+
					"verify against nothing", got, v.wantRM)
			}
		})
	}
}

// The secret is consumed as its hex STRING, not as the bytes it decodes to.
// The sibling eth derivation over the same secret does the opposite, so this is
// the single likeliest way to get the port wrong — and it is undetectable
// without a reference, since both spellings produce a valid keypair.
func TestRMDerivationUsesHexStringNotDecodedBytes(t *testing.T) {
	v := rmDerivationVectors[0]
	mint, err := base58.Decode(v.mint)
	if err != nil {
		t.Fatalf("decode mint: %v", err)
	}

	// The wrong spelling: pass the decoded bytes as if they were the string.
	decoded := make([]byte, 32)
	for i := range decoded {
		decoded[i] = 0x11
	}
	wrong := base58.Encode(deriveRewardManagerKeypair(string(decoded), mint).Public().(ed25519.PublicKey))
	if wrong == v.wantRM {
		t.Fatal("decoded-bytes and hex-string secrets derive the same reward manager; " +
			"this test can no longer detect the transposition it exists to catch")
	}
	right := base58.Encode(deriveRewardManagerKeypair(v.secret, mint).Public().(ed25519.PublicKey))
	if right != v.wantRM {
		t.Errorf("hex-string spelling derived %s, want %s", right, v.wantRM)
	}
}

// A pool whose reward manager cannot be re-derived must stop the run. The
// alternative — falling back to an unsigned create — is how the empty
// rm_owner_signature got normalized in the first place.
func TestRMKeyForPoolFailsClosed(t *testing.T) {
	const unknownRM = "HRRe6fbSDudpsBmkfBnLNHQnKkKgvhVc4pdBfR9U1YQz"
	keys := &launchpadKeys{byRM: map[string]launchpadIdentity{}}
	_, err := keys.rmKeyForPool(unknownRM)
	if err == nil {
		t.Fatal("a pool with no derivable reward manager returned a key; it must fail the run")
	}
	for _, want := range []string{unknownRM, launchpadSecretEnvVar} {
		if !strings.Contains(err.Error(), want) {
			t.Errorf("error %q does not mention %s; it should name the pool and the input to fix", err, want)
		}
	}
}

// The secret alone derives nothing, and a run configured with a secret but no
// mints would otherwise proceed to find no pool derivable and blame the secret.
func TestSecretWithoutMintsIsRejected(t *testing.T) {
	t.Setenv(launchpadSecretEnvVar, strings.Repeat("1", 64))
	t.Setenv(launchpadRotatedSecretEnvVar, strings.Repeat("2", 64))
	t.Setenv(launchpadMintsEnvVar, "")

	_, err := loadLaunchpadKeys("")
	if err == nil {
		t.Fatal("a secret with no mint list was accepted; it can derive nothing")
	}
	if !strings.Contains(err.Error(), "mint") {
		t.Errorf("error %q does not point at the missing mints", err)
	}
}

func TestSecretLengthIsValidated(t *testing.T) {
	t.Setenv(launchpadSecretEnvVar, "abcd")
	t.Setenv(launchpadRotatedSecretEnvVar, strings.Repeat("2", 64))
	t.Setenv(launchpadMintsEnvVar, rmDerivationVectors[0].mint)

	if _, err := loadLaunchpadKeys(""); err == nil {
		t.Fatal("a short secret was accepted; it would derive a parallel key universe matching no pool")
	}
}

// No secret configured is not an error at load time — the caller decides
// whether reward pools are being written at all.
// One secret alone derives half the key material, and the resulting failure is
// a per-pool "no mint derives this reward manager", which reads like a bad mint
// list rather than a missing secret. Fail up front, naming the variable.
func TestBothSecretsAreRequired(t *testing.T) {
	for _, tc := range []struct{ name, set, missing string }{
		{"only original", launchpadSecretEnvVar, launchpadRotatedSecretEnvVar},
		{"only rotated", launchpadRotatedSecretEnvVar, launchpadSecretEnvVar},
	} {
		t.Run(tc.name, func(t *testing.T) {
			t.Setenv(launchpadSecretEnvVar, "")
			t.Setenv(launchpadRotatedSecretEnvVar, "")
			t.Setenv(tc.set, strings.Repeat("1", 64))
			t.Setenv(launchpadMintsEnvVar, rmDerivationVectors[0].mint)

			_, err := loadLaunchpadKeys("")
			if err == nil {
				t.Fatalf("setting only %s was accepted; it derives half the key material", tc.set)
			}
			if !strings.Contains(err.Error(), tc.missing) {
				t.Errorf("error %q does not name the missing variable %s", err, tc.missing)
			}
		})
	}
}

func TestNoSecretYieldsNoKeys(t *testing.T) {
	t.Setenv(launchpadSecretEnvVar, "")
	t.Setenv(launchpadRotatedSecretEnvVar, "")
	keys, err := loadLaunchpadKeys("")
	if err != nil {
		t.Fatalf("absent secret should not error at load: %v", err)
	}
	if keys != nil {
		t.Error("expected nil keys with no secret")
	}
}

// Mint lists get pasted out of psql, so the parser has to survive the shapes
// that come back from one.
func TestMintListParsing(t *testing.T) {
	dir := t.TempDir()
	path := filepath.Join(dir, "mints.txt")
	content := `# launchpad mints
So11111111111111111111111111111111111111112, EPjFWdd5AufqSSqeM2qN1xzybapC8G4wEGGkZwyTDt1v
   "9n4nbM75f5Ui33ZbPYXn59EwSgE8CGsHtAeTH5YFeJ9E"
So11111111111111111111111111111111111111112
`
	if err := os.WriteFile(path, []byte(content), 0o600); err != nil {
		t.Fatalf("write mints file: %v", err)
	}
	mints, err := loadLaunchpadMints(path)
	if err != nil {
		t.Fatalf("load mints: %v", err)
	}
	if len(mints) != 3 {
		t.Fatalf("parsed %d mints (%v), want 3 deduplicated", len(mints), mints)
	}
	for _, m := range mints {
		if strings.ContainsAny(m, `",#`) {
			t.Errorf("mint %q still carries punctuation", m)
		}
	}
}

// End to end: a mint list containing a pool's mint makes that pool derivable,
// and the key that comes back is the one whose public half is the pool's RM.
func TestDerivedKeyMatchesItsRewardManager(t *testing.T) {
	v := rmDerivationVectors[0]
	t.Setenv(launchpadSecretEnvVar, v.secret)
	t.Setenv(launchpadRotatedSecretEnvVar, strings.Repeat("2", 64))
	t.Setenv(launchpadMintsEnvVar, v.mint)

	keys, err := loadLaunchpadKeys("")
	if err != nil {
		t.Fatalf("load keys: %v", err)
	}
	key, err := keys.rmKeyForPool(v.wantRM)
	if err != nil {
		t.Fatalf("pool %s should be derivable from its own mint: %v", v.wantRM, err)
	}
	if got := base58.Encode(key.Public().(ed25519.PublicKey)); got != v.wantRM {
		t.Errorf("key indexed under %s has public half %s", v.wantRM, got)
	}
}
