-- One current row per user, enforced.
--
-- 0030 added this arbiter for reposts/saves/follows/subscriptions on the
-- grounds that "only one current row per identity is an existing invariant".
-- users holds the same invariant — Create inserts a single is_current row and
-- Update mutates it in place — but was left out, and it is the one table where
-- the invariant has actually been violated.
--
-- users_pkey is (user_id, txhash), which admits a second is_current row under a
-- different txhash. Five users on a production clone (3.15M) have one, spread
-- from 2025-06 to 2026-06 — a slow drip, not a one-off. Each pair shares
-- created_at and sits a few blocks apart.
--
-- Both create paths do check first (validateUserCreate and
-- migratedUserCreateHandler both call userExists), so a single writer cannot
-- produce these: its check and its insert share a transaction. A second writer
-- can — userExists then INSERT is check-then-act, and that is not atomic across
-- transactions. Three of the five pairs put a bare-hex txhash next to a
-- 0x-prefixed one, which fits that reading, though it is inference rather than
-- a diagnosis. This index is what closes the race; the create path keeps an
-- ON CONFLICT DO NOTHING so the losing writer no-ops instead of erroring.
--
-- Five rows, but the blast radius is not five rows: anything joining an entity
-- to its owner's wallet fans out and silently duplicates every entity those
-- users own. Measured against the clone, plain joins returned 18 extra tracks
-- and 787 extra follows, which is why genesis-writer carried a DISTINCT ON
-- subquery in all fifteen of its joins.
--
-- DELIBERATELY NO BACKFILL HERE. Unlike 0030 this index cannot be created while
-- violations exist, but removing rows is not something a Go module bump should
-- do to a consumer's database: these migrations run automatically at indexer
-- start, so a `go get` would silently delete production data. The repair lives
-- in the owning application instead — see api's ddl migration
-- 0237_users_one_current_row_backfill, which deletes the duplicates and runs in
-- a pre-roll job that every serving deployment depends on, so it completes
-- before an indexer using this migration can start.
--
-- Consequence: if this runs against a database that still has duplicate current
-- rows, it fails loudly with a unique violation rather than repairing them.
-- That is the intended failure mode — it means the owning application has not
-- run its backfill yet. Databases built solely by this indexer are unaffected;
-- they cannot contain duplicates in the first place.

CREATE UNIQUE INDEX IF NOT EXISTS users_current_uniq_idx
  ON users (user_id) WHERE is_current = true;
