// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.33.0
// 	protoc        (unknown)
// source: ddex/v1beta1/pie.proto

package v1beta1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Party Identification and Enrichment (PIE) message from the DDEX standard
type PieMessage struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	MessageHeader *MessageHeader        `protobuf:"bytes,1,opt,name=message_header,json=messageHeader,proto3" json:"message_header,omitempty"`
	PartyList     *PieMessage_PartyList `protobuf:"bytes,2,opt,name=party_list,json=partyList,proto3" json:"party_list,omitempty"`
}

func (x *PieMessage) Reset() {
	*x = PieMessage{}
	if protoimpl.UnsafeEnabled {
		mi := &file_ddex_v1beta1_pie_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PieMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PieMessage) ProtoMessage() {}

func (x *PieMessage) ProtoReflect() protoreflect.Message {
	mi := &file_ddex_v1beta1_pie_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PieMessage.ProtoReflect.Descriptor instead.
func (*PieMessage) Descriptor() ([]byte, []int) {
	return file_ddex_v1beta1_pie_proto_rawDescGZIP(), []int{0}
}

func (x *PieMessage) GetMessageHeader() *MessageHeader {
	if x != nil {
		return x.MessageHeader
	}
	return nil
}

func (x *PieMessage) GetPartyList() *PieMessage_PartyList {
	if x != nil {
		return x.PartyList
	}
	return nil
}

type PieMessageAck struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// address of the PIE message
	PieAddress string `protobuf:"bytes,1,opt,name=pie_address,json=pieAddress,proto3" json:"pie_address,omitempty"`
}

func (x *PieMessageAck) Reset() {
	*x = PieMessageAck{}
	if protoimpl.UnsafeEnabled {
		mi := &file_ddex_v1beta1_pie_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PieMessageAck) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PieMessageAck) ProtoMessage() {}

func (x *PieMessageAck) ProtoReflect() protoreflect.Message {
	mi := &file_ddex_v1beta1_pie_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PieMessageAck.ProtoReflect.Descriptor instead.
func (*PieMessageAck) Descriptor() ([]byte, []int) {
	return file_ddex_v1beta1_pie_proto_rawDescGZIP(), []int{1}
}

func (x *PieMessageAck) GetPieAddress() string {
	if x != nil {
		return x.PieAddress
	}
	return ""
}

type PieMessage_PartyList struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Party []*PieMessage_Party `protobuf:"bytes,1,rep,name=party,proto3" json:"party,omitempty"`
}

func (x *PieMessage_PartyList) Reset() {
	*x = PieMessage_PartyList{}
	if protoimpl.UnsafeEnabled {
		mi := &file_ddex_v1beta1_pie_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PieMessage_PartyList) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PieMessage_PartyList) ProtoMessage() {}

func (x *PieMessage_PartyList) ProtoReflect() protoreflect.Message {
	mi := &file_ddex_v1beta1_pie_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PieMessage_PartyList.ProtoReflect.Descriptor instead.
func (*PieMessage_PartyList) Descriptor() ([]byte, []int) {
	return file_ddex_v1beta1_pie_proto_rawDescGZIP(), []int{0, 0}
}

func (x *PieMessage_PartyList) GetParty() []*PieMessage_Party {
	if x != nil {
		return x.Party
	}
	return nil
}

type PieMessage_Party struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	PartyReference string                      `protobuf:"bytes,1,opt,name=party_reference,json=partyReference,proto3" json:"party_reference,omitempty"`
	PartyId        *Party_PartyId              `protobuf:"bytes,2,opt,name=party_id,json=partyId,proto3" json:"party_id,omitempty"`
	PartyName      []*Party_PartyName          `protobuf:"bytes,3,rep,name=party_name,json=partyName,proto3" json:"party_name,omitempty"`
	PartyType      *PieMessage_Party_PartyType `protobuf:"bytes,4,opt,name=party_type,json=partyType,proto3" json:"party_type,omitempty"`
	// enrichment fields
	Biographies     []*PieMessage_Biography      `protobuf:"bytes,5,rep,name=biographies,proto3" json:"biographies,omitempty"`
	Images          []*Resource_Image            `protobuf:"bytes,6,rep,name=images,proto3" json:"images,omitempty"`
	SocialMediaUrls []*PieMessage_SocialMediaUrl `protobuf:"bytes,7,rep,name=social_media_urls,json=socialMediaUrls,proto3" json:"social_media_urls,omitempty"`
}

func (x *PieMessage_Party) Reset() {
	*x = PieMessage_Party{}
	if protoimpl.UnsafeEnabled {
		mi := &file_ddex_v1beta1_pie_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PieMessage_Party) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PieMessage_Party) ProtoMessage() {}

func (x *PieMessage_Party) ProtoReflect() protoreflect.Message {
	mi := &file_ddex_v1beta1_pie_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PieMessage_Party.ProtoReflect.Descriptor instead.
func (*PieMessage_Party) Descriptor() ([]byte, []int) {
	return file_ddex_v1beta1_pie_proto_rawDescGZIP(), []int{0, 1}
}

func (x *PieMessage_Party) GetPartyReference() string {
	if x != nil {
		return x.PartyReference
	}
	return ""
}

func (x *PieMessage_Party) GetPartyId() *Party_PartyId {
	if x != nil {
		return x.PartyId
	}
	return nil
}

func (x *PieMessage_Party) GetPartyName() []*Party_PartyName {
	if x != nil {
		return x.PartyName
	}
	return nil
}

func (x *PieMessage_Party) GetPartyType() *PieMessage_Party_PartyType {
	if x != nil {
		return x.PartyType
	}
	return nil
}

func (x *PieMessage_Party) GetBiographies() []*PieMessage_Biography {
	if x != nil {
		return x.Biographies
	}
	return nil
}

func (x *PieMessage_Party) GetImages() []*Resource_Image {
	if x != nil {
		return x.Images
	}
	return nil
}

func (x *PieMessage_Party) GetSocialMediaUrls() []*PieMessage_SocialMediaUrl {
	if x != nil {
		return x.SocialMediaUrls
	}
	return nil
}

type PieMessage_Biography struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Text   string                             `protobuf:"bytes,1,opt,name=text,proto3" json:"text,omitempty"`
	Author *PartyDescriptorWithPronounciation `protobuf:"bytes,2,opt,name=author,proto3" json:"author,omitempty"`
}

func (x *PieMessage_Biography) Reset() {
	*x = PieMessage_Biography{}
	if protoimpl.UnsafeEnabled {
		mi := &file_ddex_v1beta1_pie_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PieMessage_Biography) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PieMessage_Biography) ProtoMessage() {}

func (x *PieMessage_Biography) ProtoReflect() protoreflect.Message {
	mi := &file_ddex_v1beta1_pie_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PieMessage_Biography.ProtoReflect.Descriptor instead.
func (*PieMessage_Biography) Descriptor() ([]byte, []int) {
	return file_ddex_v1beta1_pie_proto_rawDescGZIP(), []int{0, 2}
}

func (x *PieMessage_Biography) GetText() string {
	if x != nil {
		return x.Text
	}
	return ""
}

func (x *PieMessage_Biography) GetAuthor() *PartyDescriptorWithPronounciation {
	if x != nil {
		return x.Author
	}
	return nil
}

type PieMessage_SocialMediaUrl struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Url string `protobuf:"bytes,1,opt,name=url,proto3" json:"url,omitempty"`
}

func (x *PieMessage_SocialMediaUrl) Reset() {
	*x = PieMessage_SocialMediaUrl{}
	if protoimpl.UnsafeEnabled {
		mi := &file_ddex_v1beta1_pie_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PieMessage_SocialMediaUrl) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PieMessage_SocialMediaUrl) ProtoMessage() {}

func (x *PieMessage_SocialMediaUrl) ProtoReflect() protoreflect.Message {
	mi := &file_ddex_v1beta1_pie_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PieMessage_SocialMediaUrl.ProtoReflect.Descriptor instead.
func (*PieMessage_SocialMediaUrl) Descriptor() ([]byte, []int) {
	return file_ddex_v1beta1_pie_proto_rawDescGZIP(), []int{0, 3}
}

func (x *PieMessage_SocialMediaUrl) GetUrl() string {
	if x != nil {
		return x.Url
	}
	return ""
}

type PieMessage_Party_PartyType struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Value string `protobuf:"bytes,1,opt,name=value,proto3" json:"value,omitempty"`
}

func (x *PieMessage_Party_PartyType) Reset() {
	*x = PieMessage_Party_PartyType{}
	if protoimpl.UnsafeEnabled {
		mi := &file_ddex_v1beta1_pie_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PieMessage_Party_PartyType) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PieMessage_Party_PartyType) ProtoMessage() {}

func (x *PieMessage_Party_PartyType) ProtoReflect() protoreflect.Message {
	mi := &file_ddex_v1beta1_pie_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PieMessage_Party_PartyType.ProtoReflect.Descriptor instead.
func (*PieMessage_Party_PartyType) Descriptor() ([]byte, []int) {
	return file_ddex_v1beta1_pie_proto_rawDescGZIP(), []int{0, 1, 0}
}

func (x *PieMessage_Party_PartyType) GetValue() string {
	if x != nil {
		return x.Value
	}
	return ""
}

var File_ddex_v1beta1_pie_proto protoreflect.FileDescriptor

var file_ddex_v1beta1_pie_proto_rawDesc = []byte{
	0x0a, 0x16, 0x64, 0x64, 0x65, 0x78, 0x2f, 0x76, 0x31, 0x62, 0x65, 0x74, 0x61, 0x31, 0x2f, 0x70,
	0x69, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x0c, 0x64, 0x64, 0x65, 0x78, 0x2e, 0x76,
	0x31, 0x62, 0x65, 0x74, 0x61, 0x31, 0x1a, 0x19, 0x64, 0x64, 0x65, 0x78, 0x2f, 0x76, 0x31, 0x62,
	0x65, 0x74, 0x61, 0x31, 0x2f, 0x63, 0x6f, 0x6d, 0x6d, 0x6f, 0x6e, 0x2e, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x1a, 0x18, 0x64, 0x64, 0x65, 0x78, 0x2f, 0x76, 0x31, 0x62, 0x65, 0x74, 0x61, 0x31, 0x2f,
	0x70, 0x61, 0x72, 0x74, 0x79, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x1a, 0x1b, 0x64, 0x64, 0x65,
	0x78, 0x2f, 0x76, 0x31, 0x62, 0x65, 0x74, 0x61, 0x31, 0x2f, 0x72, 0x65, 0x73, 0x6f, 0x75, 0x72,
	0x63, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0xca, 0x06, 0x0a, 0x0a, 0x50, 0x69, 0x65,
	0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x12, 0x42, 0x0a, 0x0e, 0x6d, 0x65, 0x73, 0x73, 0x61,
	0x67, 0x65, 0x5f, 0x68, 0x65, 0x61, 0x64, 0x65, 0x72, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32,
	0x1b, 0x2e, 0x64, 0x64, 0x65, 0x78, 0x2e, 0x76, 0x31, 0x62, 0x65, 0x74, 0x61, 0x31, 0x2e, 0x4d,
	0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x48, 0x65, 0x61, 0x64, 0x65, 0x72, 0x52, 0x0d, 0x6d, 0x65,
	0x73, 0x73, 0x61, 0x67, 0x65, 0x48, 0x65, 0x61, 0x64, 0x65, 0x72, 0x12, 0x41, 0x0a, 0x0a, 0x70,
	0x61, 0x72, 0x74, 0x79, 0x5f, 0x6c, 0x69, 0x73, 0x74, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32,
	0x22, 0x2e, 0x64, 0x64, 0x65, 0x78, 0x2e, 0x76, 0x31, 0x62, 0x65, 0x74, 0x61, 0x31, 0x2e, 0x50,
	0x69, 0x65, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x2e, 0x50, 0x61, 0x72, 0x74, 0x79, 0x4c,
	0x69, 0x73, 0x74, 0x52, 0x09, 0x70, 0x61, 0x72, 0x74, 0x79, 0x4c, 0x69, 0x73, 0x74, 0x1a, 0x41,
	0x0a, 0x09, 0x50, 0x61, 0x72, 0x74, 0x79, 0x4c, 0x69, 0x73, 0x74, 0x12, 0x34, 0x0a, 0x05, 0x70,
	0x61, 0x72, 0x74, 0x79, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x1e, 0x2e, 0x64, 0x64, 0x65,
	0x78, 0x2e, 0x76, 0x31, 0x62, 0x65, 0x74, 0x61, 0x31, 0x2e, 0x50, 0x69, 0x65, 0x4d, 0x65, 0x73,
	0x73, 0x61, 0x67, 0x65, 0x2e, 0x50, 0x61, 0x72, 0x74, 0x79, 0x52, 0x05, 0x70, 0x61, 0x72, 0x74,
	0x79, 0x1a, 0xe3, 0x03, 0x0a, 0x05, 0x50, 0x61, 0x72, 0x74, 0x79, 0x12, 0x27, 0x0a, 0x0f, 0x70,
	0x61, 0x72, 0x74, 0x79, 0x5f, 0x72, 0x65, 0x66, 0x65, 0x72, 0x65, 0x6e, 0x63, 0x65, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x0e, 0x70, 0x61, 0x72, 0x74, 0x79, 0x52, 0x65, 0x66, 0x65, 0x72,
	0x65, 0x6e, 0x63, 0x65, 0x12, 0x36, 0x0a, 0x08, 0x70, 0x61, 0x72, 0x74, 0x79, 0x5f, 0x69, 0x64,
	0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1b, 0x2e, 0x64, 0x64, 0x65, 0x78, 0x2e, 0x76, 0x31,
	0x62, 0x65, 0x74, 0x61, 0x31, 0x2e, 0x50, 0x61, 0x72, 0x74, 0x79, 0x2e, 0x50, 0x61, 0x72, 0x74,
	0x79, 0x49, 0x64, 0x52, 0x07, 0x70, 0x61, 0x72, 0x74, 0x79, 0x49, 0x64, 0x12, 0x3c, 0x0a, 0x0a,
	0x70, 0x61, 0x72, 0x74, 0x79, 0x5f, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x03, 0x20, 0x03, 0x28, 0x0b,
	0x32, 0x1d, 0x2e, 0x64, 0x64, 0x65, 0x78, 0x2e, 0x76, 0x31, 0x62, 0x65, 0x74, 0x61, 0x31, 0x2e,
	0x50, 0x61, 0x72, 0x74, 0x79, 0x2e, 0x50, 0x61, 0x72, 0x74, 0x79, 0x4e, 0x61, 0x6d, 0x65, 0x52,
	0x09, 0x70, 0x61, 0x72, 0x74, 0x79, 0x4e, 0x61, 0x6d, 0x65, 0x12, 0x47, 0x0a, 0x0a, 0x70, 0x61,
	0x72, 0x74, 0x79, 0x5f, 0x74, 0x79, 0x70, 0x65, 0x18, 0x04, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x28,
	0x2e, 0x64, 0x64, 0x65, 0x78, 0x2e, 0x76, 0x31, 0x62, 0x65, 0x74, 0x61, 0x31, 0x2e, 0x50, 0x69,
	0x65, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x2e, 0x50, 0x61, 0x72, 0x74, 0x79, 0x2e, 0x50,
	0x61, 0x72, 0x74, 0x79, 0x54, 0x79, 0x70, 0x65, 0x52, 0x09, 0x70, 0x61, 0x72, 0x74, 0x79, 0x54,
	0x79, 0x70, 0x65, 0x12, 0x44, 0x0a, 0x0b, 0x62, 0x69, 0x6f, 0x67, 0x72, 0x61, 0x70, 0x68, 0x69,
	0x65, 0x73, 0x18, 0x05, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x22, 0x2e, 0x64, 0x64, 0x65, 0x78, 0x2e,
	0x76, 0x31, 0x62, 0x65, 0x74, 0x61, 0x31, 0x2e, 0x50, 0x69, 0x65, 0x4d, 0x65, 0x73, 0x73, 0x61,
	0x67, 0x65, 0x2e, 0x42, 0x69, 0x6f, 0x67, 0x72, 0x61, 0x70, 0x68, 0x79, 0x52, 0x0b, 0x62, 0x69,
	0x6f, 0x67, 0x72, 0x61, 0x70, 0x68, 0x69, 0x65, 0x73, 0x12, 0x34, 0x0a, 0x06, 0x69, 0x6d, 0x61,
	0x67, 0x65, 0x73, 0x18, 0x06, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x1c, 0x2e, 0x64, 0x64, 0x65, 0x78,
	0x2e, 0x76, 0x31, 0x62, 0x65, 0x74, 0x61, 0x31, 0x2e, 0x52, 0x65, 0x73, 0x6f, 0x75, 0x72, 0x63,
	0x65, 0x2e, 0x49, 0x6d, 0x61, 0x67, 0x65, 0x52, 0x06, 0x69, 0x6d, 0x61, 0x67, 0x65, 0x73, 0x12,
	0x53, 0x0a, 0x11, 0x73, 0x6f, 0x63, 0x69, 0x61, 0x6c, 0x5f, 0x6d, 0x65, 0x64, 0x69, 0x61, 0x5f,
	0x75, 0x72, 0x6c, 0x73, 0x18, 0x07, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x27, 0x2e, 0x64, 0x64, 0x65,
	0x78, 0x2e, 0x76, 0x31, 0x62, 0x65, 0x74, 0x61, 0x31, 0x2e, 0x50, 0x69, 0x65, 0x4d, 0x65, 0x73,
	0x73, 0x61, 0x67, 0x65, 0x2e, 0x53, 0x6f, 0x63, 0x69, 0x61, 0x6c, 0x4d, 0x65, 0x64, 0x69, 0x61,
	0x55, 0x72, 0x6c, 0x52, 0x0f, 0x73, 0x6f, 0x63, 0x69, 0x61, 0x6c, 0x4d, 0x65, 0x64, 0x69, 0x61,
	0x55, 0x72, 0x6c, 0x73, 0x1a, 0x21, 0x0a, 0x09, 0x50, 0x61, 0x72, 0x74, 0x79, 0x54, 0x79, 0x70,
	0x65, 0x12, 0x14, 0x0a, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x1a, 0x68, 0x0a, 0x09, 0x42, 0x69, 0x6f, 0x67, 0x72,
	0x61, 0x70, 0x68, 0x79, 0x12, 0x12, 0x0a, 0x04, 0x74, 0x65, 0x78, 0x74, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x04, 0x74, 0x65, 0x78, 0x74, 0x12, 0x47, 0x0a, 0x06, 0x61, 0x75, 0x74, 0x68,
	0x6f, 0x72, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x2f, 0x2e, 0x64, 0x64, 0x65, 0x78, 0x2e,
	0x76, 0x31, 0x62, 0x65, 0x74, 0x61, 0x31, 0x2e, 0x50, 0x61, 0x72, 0x74, 0x79, 0x44, 0x65, 0x73,
	0x63, 0x72, 0x69, 0x70, 0x74, 0x6f, 0x72, 0x57, 0x69, 0x74, 0x68, 0x50, 0x72, 0x6f, 0x6e, 0x6f,
	0x75, 0x6e, 0x63, 0x69, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x52, 0x06, 0x61, 0x75, 0x74, 0x68, 0x6f,
	0x72, 0x1a, 0x22, 0x0a, 0x0e, 0x53, 0x6f, 0x63, 0x69, 0x61, 0x6c, 0x4d, 0x65, 0x64, 0x69, 0x61,
	0x55, 0x72, 0x6c, 0x12, 0x10, 0x0a, 0x03, 0x75, 0x72, 0x6c, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x03, 0x75, 0x72, 0x6c, 0x22, 0x30, 0x0a, 0x0d, 0x50, 0x69, 0x65, 0x4d, 0x65, 0x73, 0x73,
	0x61, 0x67, 0x65, 0x41, 0x63, 0x6b, 0x12, 0x1f, 0x0a, 0x0b, 0x70, 0x69, 0x65, 0x5f, 0x61, 0x64,
	0x64, 0x72, 0x65, 0x73, 0x73, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0a, 0x70, 0x69, 0x65,
	0x41, 0x64, 0x64, 0x72, 0x65, 0x73, 0x73, 0x42, 0x37, 0x5a, 0x35, 0x67, 0x69, 0x74, 0x68, 0x75,
	0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x41, 0x75, 0x64, 0x69, 0x75, 0x73, 0x50, 0x72, 0x6f, 0x6a,
	0x65, 0x63, 0x74, 0x2f, 0x61, 0x75, 0x64, 0x69, 0x75, 0x73, 0x64, 0x2f, 0x70, 0x6b, 0x67, 0x2f,
	0x61, 0x70, 0x69, 0x2f, 0x64, 0x64, 0x65, 0x78, 0x2f, 0x76, 0x31, 0x62, 0x65, 0x74, 0x61, 0x31,
	0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_ddex_v1beta1_pie_proto_rawDescOnce sync.Once
	file_ddex_v1beta1_pie_proto_rawDescData = file_ddex_v1beta1_pie_proto_rawDesc
)

func file_ddex_v1beta1_pie_proto_rawDescGZIP() []byte {
	file_ddex_v1beta1_pie_proto_rawDescOnce.Do(func() {
		file_ddex_v1beta1_pie_proto_rawDescData = protoimpl.X.CompressGZIP(file_ddex_v1beta1_pie_proto_rawDescData)
	})
	return file_ddex_v1beta1_pie_proto_rawDescData
}

var file_ddex_v1beta1_pie_proto_msgTypes = make([]protoimpl.MessageInfo, 7)
var file_ddex_v1beta1_pie_proto_goTypes = []interface{}{
	(*PieMessage)(nil),                        // 0: ddex.v1beta1.PieMessage
	(*PieMessageAck)(nil),                     // 1: ddex.v1beta1.PieMessageAck
	(*PieMessage_PartyList)(nil),              // 2: ddex.v1beta1.PieMessage.PartyList
	(*PieMessage_Party)(nil),                  // 3: ddex.v1beta1.PieMessage.Party
	(*PieMessage_Biography)(nil),              // 4: ddex.v1beta1.PieMessage.Biography
	(*PieMessage_SocialMediaUrl)(nil),         // 5: ddex.v1beta1.PieMessage.SocialMediaUrl
	(*PieMessage_Party_PartyType)(nil),        // 6: ddex.v1beta1.PieMessage.Party.PartyType
	(*MessageHeader)(nil),                     // 7: ddex.v1beta1.MessageHeader
	(*Party_PartyId)(nil),                     // 8: ddex.v1beta1.Party.PartyId
	(*Party_PartyName)(nil),                   // 9: ddex.v1beta1.Party.PartyName
	(*Resource_Image)(nil),                    // 10: ddex.v1beta1.Resource.Image
	(*PartyDescriptorWithPronounciation)(nil), // 11: ddex.v1beta1.PartyDescriptorWithPronounciation
}
var file_ddex_v1beta1_pie_proto_depIdxs = []int32{
	7,  // 0: ddex.v1beta1.PieMessage.message_header:type_name -> ddex.v1beta1.MessageHeader
	2,  // 1: ddex.v1beta1.PieMessage.party_list:type_name -> ddex.v1beta1.PieMessage.PartyList
	3,  // 2: ddex.v1beta1.PieMessage.PartyList.party:type_name -> ddex.v1beta1.PieMessage.Party
	8,  // 3: ddex.v1beta1.PieMessage.Party.party_id:type_name -> ddex.v1beta1.Party.PartyId
	9,  // 4: ddex.v1beta1.PieMessage.Party.party_name:type_name -> ddex.v1beta1.Party.PartyName
	6,  // 5: ddex.v1beta1.PieMessage.Party.party_type:type_name -> ddex.v1beta1.PieMessage.Party.PartyType
	4,  // 6: ddex.v1beta1.PieMessage.Party.biographies:type_name -> ddex.v1beta1.PieMessage.Biography
	10, // 7: ddex.v1beta1.PieMessage.Party.images:type_name -> ddex.v1beta1.Resource.Image
	5,  // 8: ddex.v1beta1.PieMessage.Party.social_media_urls:type_name -> ddex.v1beta1.PieMessage.SocialMediaUrl
	11, // 9: ddex.v1beta1.PieMessage.Biography.author:type_name -> ddex.v1beta1.PartyDescriptorWithPronounciation
	10, // [10:10] is the sub-list for method output_type
	10, // [10:10] is the sub-list for method input_type
	10, // [10:10] is the sub-list for extension type_name
	10, // [10:10] is the sub-list for extension extendee
	0,  // [0:10] is the sub-list for field type_name
}

func init() { file_ddex_v1beta1_pie_proto_init() }
func file_ddex_v1beta1_pie_proto_init() {
	if File_ddex_v1beta1_pie_proto != nil {
		return
	}
	file_ddex_v1beta1_common_proto_init()
	file_ddex_v1beta1_party_proto_init()
	file_ddex_v1beta1_resource_proto_init()
	if !protoimpl.UnsafeEnabled {
		file_ddex_v1beta1_pie_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PieMessage); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_ddex_v1beta1_pie_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PieMessageAck); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_ddex_v1beta1_pie_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PieMessage_PartyList); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_ddex_v1beta1_pie_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PieMessage_Party); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_ddex_v1beta1_pie_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PieMessage_Biography); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_ddex_v1beta1_pie_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PieMessage_SocialMediaUrl); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_ddex_v1beta1_pie_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PieMessage_Party_PartyType); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_ddex_v1beta1_pie_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   7,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_ddex_v1beta1_pie_proto_goTypes,
		DependencyIndexes: file_ddex_v1beta1_pie_proto_depIdxs,
		MessageInfos:      file_ddex_v1beta1_pie_proto_msgTypes,
	}.Build()
	File_ddex_v1beta1_pie_proto = out.File
	file_ddex_v1beta1_pie_proto_rawDesc = nil
	file_ddex_v1beta1_pie_proto_goTypes = nil
	file_ddex_v1beta1_pie_proto_depIdxs = nil
}
