// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package db

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type EthFundingRound struct {
	RoundNum     int32            `json:"round_num"`
	Blocknumber  int64            `json:"blocknumber"`
	CreationTime pgtype.Timestamp `json:"creation_time"`
}

type EthRegisteredEndpoint struct {
	ID             int32  `json:"id"`
	ServiceType    string `json:"service_type"`
	Owner          string `json:"owner"`
	DelegateWallet string `json:"delegate_wallet"`
	Endpoint       string `json:"endpoint"`
	Blocknumber    int64  `json:"blocknumber"`
}

type EthServiceProvider struct {
	Address           string `json:"address"`
	DeployerStake     int64  `json:"deployer_stake"`
	DeployerCut       int64  `json:"deployer_cut"`
	ValidBounds       bool   `json:"valid_bounds"`
	NumberOfEndpoints int32  `json:"number_of_endpoints"`
	MinAccountStake   int64  `json:"min_account_stake"`
	MaxAccountStake   int64  `json:"max_account_stake"`
}
