// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

type Querier interface {
	GetAllEthAddressesOfRegisteredNodes(ctx context.Context) ([]string, error)
	GetAllRegisteredNodes(ctx context.Context) ([]CoreValidator, error)
	GetAllRegisteredNodesSorted(ctx context.Context) ([]CoreValidator, error)
	GetAppStateAtHeight(ctx context.Context, blockHeight int64) (GetAppStateAtHeightRow, error)
	GetAvailableCities(ctx context.Context, arg GetAvailableCitiesParams) ([]GetAvailableCitiesRow, error)
	GetAvailableCountries(ctx context.Context, limit int32) ([]GetAvailableCountriesRow, error)
	GetAvailableRegions(ctx context.Context, arg GetAvailableRegionsParams) ([]GetAvailableRegionsRow, error)
	GetBlock(ctx context.Context, height int64) (CoreBlock, error)
	GetBlockTransactions(ctx context.Context, blockID int64) ([]CoreTransaction, error)
	GetDecodedPlays(ctx context.Context, limit int32) ([]GetDecodedPlaysRow, error)
	GetDecodedPlaysByLocation(ctx context.Context, arg GetDecodedPlaysByLocationParams) ([]GetDecodedPlaysByLocationRow, error)
	GetDecodedPlaysByTimeRange(ctx context.Context, arg GetDecodedPlaysByTimeRangeParams) ([]GetDecodedPlaysByTimeRangeRow, error)
	GetDecodedPlaysByTrack(ctx context.Context, arg GetDecodedPlaysByTrackParams) ([]GetDecodedPlaysByTrackRow, error)
	GetDecodedPlaysByUser(ctx context.Context, arg GetDecodedPlaysByUserParams) ([]GetDecodedPlaysByUserRow, error)
	GetDecodedTx(ctx context.Context, txHash string) (CoreEtlTx, error)
	GetDecodedTxsByBlock(ctx context.Context, blockHeight int64) ([]CoreEtlTx, error)
	GetDecodedTxsByType(ctx context.Context, arg GetDecodedTxsByTypeParams) ([]CoreEtlTx, error)
	GetInProgressRollupReports(ctx context.Context) ([]SlaNodeReport, error)
	GetLatestAppState(ctx context.Context) (GetLatestAppStateRow, error)
	GetLatestBlock(ctx context.Context) (CoreBlock, error)
	GetLatestDecodedTxs(ctx context.Context, limit int32) ([]CoreEtlTx, error)
	GetLatestSlaRollup(ctx context.Context) (SlaRollup, error)
	GetNodeByEndpoint(ctx context.Context, endpoint string) (CoreValidator, error)
	GetNodesByEndpoints(ctx context.Context, dollar_1 []string) ([]CoreValidator, error)
	GetPreviousSlaRollupFromId(ctx context.Context, id int32) (SlaRollup, error)
	GetRecentBlocks(ctx context.Context, limit int32) ([]CoreBlock, error)
	GetRecentRollupsForAllNodes(ctx context.Context, arg GetRecentRollupsForAllNodesParams) ([]GetRecentRollupsForAllNodesRow, error)
	GetRecentRollupsForNode(ctx context.Context, address string) ([]GetRecentRollupsForNodeRow, error)
	GetRecentTxs(ctx context.Context, limit int32) ([]CoreTransaction, error)
	GetRecordingsForTrack(ctx context.Context, trackID string) ([]SoundRecording, error)
	GetRegisteredNodeByCometAddress(ctx context.Context, cometAddress string) (CoreValidator, error)
	GetRegisteredNodeByEthAddress(ctx context.Context, ethAddress string) (CoreValidator, error)
	GetRegisteredNodesByType(ctx context.Context, nodeType string) ([]CoreValidator, error)
	GetRollupReportForNodeAndId(ctx context.Context, arg GetRollupReportForNodeAndIdParams) (SlaNodeReport, error)
	GetRollupReportsForId(ctx context.Context, slaRollupID pgtype.Int4) ([]SlaNodeReport, error)
	GetSlaRollupWithId(ctx context.Context, id int32) (SlaRollup, error)
	GetSlaRollupWithTimestamp(ctx context.Context, time pgtype.Timestamp) (SlaRollup, error)
	GetStorageProof(ctx context.Context, arg GetStorageProofParams) (StorageProof, error)
	GetStorageProofPeers(ctx context.Context, blockHeight int64) ([]string, error)
	GetStorageProofRollups(ctx context.Context, arg GetStorageProofRollupsParams) ([]GetStorageProofRollupsRow, error)
	GetStorageProofs(ctx context.Context, blockHeight int64) ([]StorageProof, error)
	GetStorageProofsForNodeInRange(ctx context.Context, arg GetStorageProofsForNodeInRangeParams) ([]StorageProof, error)
	GetTx(ctx context.Context, lower string) (CoreTransaction, error)
	HasAccessToTrackRelease(ctx context.Context, arg HasAccessToTrackReleaseParams) (bool, error)
	TotalBlocks(ctx context.Context) (int64, error)
	TotalTransactions(ctx context.Context) (int64, error)
	TotalTransactionsByType(ctx context.Context, txType string) (int64, error)
	TotalTxResults(ctx context.Context) (int64, error)
	TotalValidators(ctx context.Context) (int64, error)
	TxsPerHour(ctx context.Context) ([]TxsPerHourRow, error)
}

var _ Querier = (*Queries)(nil)
