package entity_manager

import (
	"context"
)

type playlistCreateHandler struct{}

func (h *playlistCreateHandler) EntityType() string { return EntityTypePlaylist }
func (h *playlistCreateHandler) Action() string     { return ActionCreate }

func (h *playlistCreateHandler) Handle(ctx context.Context, params *Params) error {
	if err := validatePlaylistCreate(ctx, params); err != nil {
		return err
	}
	return insertPlaylistAndRoute(ctx, params)
}

func validatePlaylistCreate(ctx context.Context, params *Params) error {
	if params.EntityType != EntityTypePlaylist {
		return NewValidationError("wrong entity type %s", params.EntityType)
	}
	if params.Action != ActionCreate {
		return NewValidationError("wrong action %s", params.Action)
	}
	if params.EntityID < PlaylistIDOffset {
		return NewValidationError("playlist id %d below offset %d", params.EntityID, PlaylistIDOffset)
	}
	if params.Metadata == nil {
		return NewValidationError("metadata is required for playlist creation")
	}
	if desc := params.MetadataString("description"); desc != "" {
		if err := ValidateDescription(desc); err != nil {
			return err
		}
	}
	if err := ValidateSigner(ctx, params); err != nil {
		return err
	}
	exists, err := playlistExists(ctx, params.DBTX, params.EntityID)
	if err != nil {
		return err
	}
	if exists {
		return NewValidationError("playlist %d already exists", params.EntityID)
	}
	return nil
}

// playlistRoute is a playlist's route as it already exists elsewhere, carried
// verbatim instead of being recomputed.
type playlistRoute struct {
	Slug        string
	TitleSlug   string
	CollisionID int
}

// playlistState is the non-metadata state a playlist is created with.
// Production passes the zero value; only the migration replay fills it in.
type playlistState struct {
	IsDelete bool

	// Route, when set, replaces slug generation. As with tracks, legacy slugs
	// are not reproducible from the title: on a production clone 189,626 of
	// 312,552 migrated playlists regenerate to a slug different from the one
	// they serve today -- 142,949 because the old scheme appended the playlist
	// id, the rest over punctuation and collision numbering. 106,833 of those
	// still resolve through the legacy id-suffixed row written below, but the
	// remaining 82,793 appear nowhere in the regenerated data and would stop
	// resolving entirely. A slug is a permanent URL, so the migration carries
	// the real one rather than deriving a plausible one.
	Route *playlistRoute

	// RemovedTracks are the playlist's tombstones — tracks that were once in it
	// and have since left. A Create can only produce live membership on its own,
	// so the migration carries the removal history explicitly; see
	// insertPlaylistTrackTombstones for why it cannot be derived and why it
	// matters.
	RemovedTracks []removedPlaylistTrack
}

// insertPlaylistAndRoute writes a newly created playlist. A new playlist is
// never created already-deleted; only the genesis migration replays a deleted
// row, via insertPlaylistAndRouteWithState.
func insertPlaylistAndRoute(ctx context.Context, params *Params) error {
	return insertPlaylistAndRouteWithState(ctx, params, playlistState{})
}

func insertPlaylistAndRouteWithState(ctx context.Context, params *Params, state playlistState) error {
	playlistName := params.MetadataString("playlist_name")
	description := params.MetadataString("description")
	isAlbum := params.MetadataBoolOr("is_album", false)
	isPrivate := params.MetadataBoolOr("is_private", false)
	isImageAutogenerated := params.MetadataBoolOr("is_image_autogenerated", false)
	isStreamGated := params.MetadataBoolOr("is_stream_gated", false)
	isScheduledRelease := params.MetadataBoolOr("is_scheduled_release", false)

	playlistImageMultihash := params.MetadataString("playlist_image_multihash")
	playlistImageSizesMultihash := params.MetadataString("playlist_image_sizes_multihash")
	ddexApp := params.MetadataString("ddex_app")
	upc := params.MetadataString("upc")
	parentalWarningType := params.MetadataString("parental_warning_type")

	playlistContents := metadataPlaylistContentsJSON(params)
	streamConditions := metadataJSONRaw(params, "stream_conditions")
	ddexReleaseIDs := metadataJSONRaw(params, "ddex_release_ids")
	artists := metadataJSONRaw(params, "artists")
	copyrightLine := metadataJSONRaw(params, "copyright_line")
	producerCopyrightLine := metadataJSONRaw(params, "producer_copyright_line")

	releaseDate := releaseDateOrDefault(params.MetadataString("release_date"), params.BlockTime)

	row := &playlistRow{
		PlaylistID:                  params.EntityID,
		PlaylistOwnerID:             params.UserID,
		PlaylistName:                nullStringPtr(playlistName),
		Description:                 nullStringPtr(description),
		IsAlbum:                     isAlbum,
		IsPrivate:                   isPrivate,
		PlaylistContents:            playlistContents,
		PlaylistImageMultihash:      nullStringPtr(playlistImageMultihash),
		PlaylistImageSizesMultihash: nullStringPtr(playlistImageSizesMultihash),
		IsImageAutogenerated:        isImageAutogenerated,
		IsStreamGated:               isStreamGated,
		StreamConditions:            streamConditions,
		IsScheduledRelease:          isScheduledRelease,
		ReleaseDate:                 releaseDate,
		UPC:                         nullStringPtr(upc),
		DdexApp:                     nullStringPtr(ddexApp),
		DdexReleaseIDs:              ddexReleaseIDs,
		Artists:                     artists,
		CopyrightLine:               copyrightLine,
		ProducerCopyrightLine:       producerCopyrightLine,
		ParentalWarningType:         nullStringPtr(parentalWarningType),
		CreatedAt:                   params.BlockTime,
	}

	trackIDs := extractPlaylistTrackIDs(params.Metadata)

	// last_added_to is the block time of the most recent track add; set it when
	// the playlist is created with tracks (matches the legacy indexer), else NULL.
	if len(trackIDs) > 0 {
		row.LastAddedTo = pgTimestamp(params.BlockTime)
	}

	if err := insertPlaylistRow(ctx, params.DBTX, row, state.IsDelete, params.BlockTime, params.TxHash, params.BlockNumber); err != nil {
		return err
	}

	if err := updatePlaylistTracks(ctx, params.DBTX, params.EntityID, params.Metadata, params.BlockTime); err != nil {
		return err
	}
	// Tombstones are written after the live rows so the live membership wins any
	// contradiction between the two. Empty for a real create — only the
	// migration carries removal history.
	if err := insertPlaylistTrackTombstones(ctx, params.DBTX, params.EntityID, state.RemovedTracks, trackIDs, params.BlockTime); err != nil {
		return err
	}
	if err := updateAlbumPriceHistory(ctx, params.DBTX, params.EntityID, params.BlockNumber, params.BlockTime, params.Metadata); err != nil {
		return err
	}

	// Insert playlist routes if a name is provided. Two rows get written:
	//
	//   1. The current route — `<sanitized-title>` (with a numeric `-N`
	//      collision suffix appended if another playlist by this owner
	//      already claimed the same slug). This is the canonical URL. A
	//      migration replay supplies this route instead of deriving it, so the
	//      playlist keeps serving the URL it serves today (see playlistState).
	//
	//   2. A NON-current "legacy ID-suffixed" route of the form
	//      `<sanitized-title>-<playlist_id>`. Before collision-aware routing,
	//      every playlist URL was just `<slug>-<playlist_id>`. Shared/bookmarked
	//      URLs from that era keep resolving because we still record this row.
	//      Skipped when it would equal the current slug — e.g. a playlist
	//      named literally `my-playlist-400123`.
	if playlistName != "" {
		var (
			currentSlug string
			titleSlug   string
			collisionID int
		)
		if state.Route != nil {
			currentSlug, titleSlug, collisionID = state.Route.Slug, state.Route.TitleSlug, state.Route.CollisionID
		} else {
			var err error
			currentSlug, titleSlug, collisionID, err = GeneratePlaylistSlugAndCollisionID(ctx, params.DBTX, params.UserID, params.EntityID, playlistName)
			if err != nil {
				return err
			}
		}
		_, err := params.DBTX.Exec(ctx, `
			INSERT INTO playlist_routes (
				slug, title_slug, collision_id, owner_id, playlist_id, is_current,
				blockhash, blocknumber, txhash
			) VALUES (
				$1, $2, $3, $4, $5, true,
				$6, $7, $8
			)
		`, currentSlug, titleSlug, collisionID, params.UserID, params.EntityID, params.BlockHash, params.BlockNumber, params.TxHash)
		if err != nil {
			return err
		}

		// Legacy ID-suffixed slug: SanitizeSlug appends `-<collision_id>`
		// when the collision id is non-zero, so passing playlist_id as the
		// collision_id produces `<title>-<playlist_id>`.
		legacyIDSlug := SanitizeSlug(playlistName, params.EntityID, int(params.EntityID))
		if legacyIDSlug != currentSlug {
			_, err = params.DBTX.Exec(ctx, `
				INSERT INTO playlist_routes (
					slug, title_slug, collision_id, owner_id, playlist_id, is_current,
					blockhash, blocknumber, txhash
				) VALUES (
					$1, $2, $3, $4, $5, false,
					$6, $7, $8
				)
				ON CONFLICT (owner_id, slug) DO NOTHING
			`, legacyIDSlug, legacyIDSlug, collisionID, params.UserID, params.EntityID, params.BlockHash, params.BlockNumber, params.TxHash)
			if err != nil {
				return err
			}
		}
	}

	return nil
}

// nullStringPtr returns a *string for non-empty strings, nil for empty.
func nullStringPtr(s string) *string {
	if s == "" {
		return nil
	}
	return &s
}

// PlaylistCreate returns the Playlist Create handler.
func PlaylistCreate() Handler { return &playlistCreateHandler{} }
