package entity_manager

import (
	"context"
	"time"

	"github.com/jackc/pgx/v5/pgtype"
)

type playlistCreateHandler struct{}

func (h *playlistCreateHandler) EntityType() string { return EntityTypePlaylist }
func (h *playlistCreateHandler) Action() string     { return ActionCreate }

func (h *playlistCreateHandler) Handle(ctx context.Context, params *Params) error {
	if err := validatePlaylistCreate(ctx, params); err != nil {
		return err
	}
	return insertPlaylistAndRoute(ctx, params)
}

func validatePlaylistCreate(ctx context.Context, params *Params) error {
	if params.EntityType != EntityTypePlaylist {
		return NewValidationError("wrong entity type %s", params.EntityType)
	}
	if params.Action != ActionCreate {
		return NewValidationError("wrong action %s", params.Action)
	}
	if params.EntityID < PlaylistIDOffset {
		return NewValidationError("playlist id %d below offset %d", params.EntityID, PlaylistIDOffset)
	}
	if params.Metadata == nil {
		return NewValidationError("metadata is required for playlist creation")
	}
	if desc := params.MetadataString("description"); desc != "" {
		if err := ValidateDescription(desc); err != nil {
			return err
		}
	}
	if err := ValidateSigner(ctx, params); err != nil {
		return err
	}
	exists, err := playlistExists(ctx, params.DBTX, params.EntityID)
	if err != nil {
		return err
	}
	if exists {
		return NewValidationError("playlist %d already exists", params.EntityID)
	}
	return nil
}

func insertPlaylistAndRoute(ctx context.Context, params *Params) error {
	playlistName := params.MetadataString("playlist_name")
	description := params.MetadataString("description")
	isAlbum := params.MetadataBoolOr("is_album", false)
	isPrivate := params.MetadataBoolOr("is_private", false)
	isImageAutogenerated := params.MetadataBoolOr("is_image_autogenerated", false)
	isStreamGated := params.MetadataBoolOr("is_stream_gated", false)
	isScheduledRelease := params.MetadataBoolOr("is_scheduled_release", false)

	playlistImageMultihash := params.MetadataString("playlist_image_multihash")
	playlistImageSizesMultihash := params.MetadataString("playlist_image_sizes_multihash")
	ddexApp := params.MetadataString("ddex_app")
	upc := params.MetadataString("upc")
	parentalWarningType := params.MetadataString("parental_warning_type")

	playlistContents := metadataPlaylistContentsJSON(params)
	streamConditions := metadataJSONRaw(params, "stream_conditions")
	ddexReleaseIDs := metadataJSONRaw(params, "ddex_release_ids")
	artists := metadataJSONRaw(params, "artists")
	copyrightLine := metadataJSONRaw(params, "copyright_line")
	producerCopyrightLine := metadataJSONRaw(params, "producer_copyright_line")

	var releaseDate pgtype.Timestamp
	if rd := params.MetadataString("release_date"); rd != "" {
		if t, err := time.Parse(time.RFC3339, rd); err == nil {
			releaseDate = pgtype.Timestamp{Time: t, Valid: true}
		}
	}

	row := &playlistRow{
		PlaylistID:                  params.EntityID,
		PlaylistOwnerID:             params.UserID,
		PlaylistName:                nullStringPtr(playlistName),
		Description:                 nullStringPtr(description),
		IsAlbum:                     isAlbum,
		IsPrivate:                   isPrivate,
		PlaylistContents:            playlistContents,
		PlaylistImageMultihash:      nullStringPtr(playlistImageMultihash),
		PlaylistImageSizesMultihash: nullStringPtr(playlistImageSizesMultihash),
		IsImageAutogenerated:        isImageAutogenerated,
		IsStreamGated:               isStreamGated,
		StreamConditions:            streamConditions,
		IsScheduledRelease:          isScheduledRelease,
		ReleaseDate:                 releaseDate,
		UPC:                         nullStringPtr(upc),
		DdexApp:                     nullStringPtr(ddexApp),
		DdexReleaseIDs:              ddexReleaseIDs,
		Artists:                     artists,
		CopyrightLine:               copyrightLine,
		ProducerCopyrightLine:       producerCopyrightLine,
		ParentalWarningType:         nullStringPtr(parentalWarningType),
		CreatedAt:                   params.BlockTime,
	}

	if err := insertPlaylistRow(ctx, params.DBTX, row, false, params.BlockTime, params.TxHash, params.BlockNumber); err != nil {
		return err
	}

	if err := updatePlaylistTracks(ctx, params.DBTX, params.EntityID, params.Metadata); err != nil {
		return err
	}
	if err := updateAlbumPriceHistory(ctx, params.DBTX, params.EntityID, params.BlockNumber, params.BlockTime, params.Metadata); err != nil {
		return err
	}

	// Insert playlist routes if a name is provided. Two rows get written:
	//
	//   1. The current route — `<sanitized-title>` (with a numeric `-N`
	//      collision suffix appended if another playlist by this owner
	//      already claimed the same slug). This is the canonical URL.
	//
	//   2. A NON-current "legacy ID-suffixed" route of the form
	//      `<sanitized-title>-<playlist_id>`. Before collision-aware routing,
	//      every playlist URL was just `<slug>-<playlist_id>`. Shared/bookmarked
	//      URLs from that era keep resolving because we still record this row.
	//      Skipped when it would equal the current slug — e.g. a playlist
	//      named literally `my-playlist-400123`.
	if playlistName != "" {
		currentSlug, titleSlug, collisionID, err := GeneratePlaylistSlugAndCollisionID(ctx, params.DBTX, params.UserID, params.EntityID, playlistName)
		if err != nil {
			return err
		}
		_, err = params.DBTX.Exec(ctx, `
			INSERT INTO playlist_routes (
				slug, title_slug, collision_id, owner_id, playlist_id, is_current,
				blockhash, blocknumber, txhash
			) VALUES (
				$1, $2, $3, $4, $5, true,
				$6, $7, $8
			)
		`, currentSlug, titleSlug, collisionID, params.UserID, params.EntityID, params.BlockHash, params.BlockNumber, params.TxHash)
		if err != nil {
			return err
		}

		// Legacy ID-suffixed slug: SanitizeSlug appends `-<collision_id>`
		// when the collision id is non-zero, so passing playlist_id as the
		// collision_id produces `<title>-<playlist_id>`.
		legacyIDSlug := SanitizeSlug(playlistName, params.EntityID, int(params.EntityID))
		if legacyIDSlug != currentSlug {
			_, err = params.DBTX.Exec(ctx, `
				INSERT INTO playlist_routes (
					slug, title_slug, collision_id, owner_id, playlist_id, is_current,
					blockhash, blocknumber, txhash
				) VALUES (
					$1, $2, $3, $4, $5, false,
					$6, $7, $8
				)
				ON CONFLICT (owner_id, slug) DO NOTHING
			`, legacyIDSlug, legacyIDSlug, collisionID, params.UserID, params.EntityID, params.BlockHash, params.BlockNumber, params.TxHash)
			if err != nil {
				return err
			}
		}
	}

	return nil
}

// nullStringPtr returns a *string for non-empty strings, nil for empty.
func nullStringPtr(s string) *string {
	if s == "" {
		return nil
	}
	return &s
}

// PlaylistCreate returns the Playlist Create handler.
func PlaylistCreate() Handler { return &playlistCreateHandler{} }
